"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import type { ItemState, Priority } from "@cvg/contracts";
import { apiFetch, formatRelativeTime } from "./api-client";
import { PriorityBadge, StatusBadge } from "./status-badge";

interface QueueItem { id: string; requestId: string; status: ItemState; priority: Priority; dueAt: string; createdAt: string; requestCode: string; nextAction: string; overdue: boolean; patient: { displayName: string; species: string; externalId: string }; service: { name: string } }
export function QueueView() {
  const [items, setItems] = useState<QueueItem[]>([]); const [department, setDepartment] = useState("INPATIENT"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [overdue, setOverdue] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const me = await apiFetch<{ user: { departmentCode: string } }>("/session/me"); setDepartment(me.user.departmentCode); const queue = await apiFetch<QueueItem[]>(`/queues/${me.user.departmentCode}/items?${overdue ? "overdue=true" : ""}`); setItems(queue); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar a fila."); } finally { setLoading(false); } }, [overdue]);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { const refresh = () => { void load(); }; window.addEventListener("cvg:realtime-updated", refresh); window.addEventListener("cvg:realtime-resync", refresh); return () => { window.removeEventListener("cvg:realtime-updated", refresh); window.removeEventListener("cvg:realtime-resync", refresh); }; }, [load]);
  return <div className="queue-page"><div className="page-heading"><div><p className="eyebrow">Operação · {department}</p><h1>Central de <em>exames.</em></h1><p className="page-lede">A próxima ação de cada item, na ordem certa.</p></div><div className="queue-actions"><label className="toggle"><input type="checkbox" checked={overdue} onChange={(event) => setOverdue(event.target.checked)} /><span />Somente atrasados</label><button className="button button-ghost" onClick={() => void load()}>↻ Atualizar</button></div></div>{error && <div className="error-state" role="alert">{error}<button className="button button-ghost" onClick={() => void load()}>Tentar novamente</button></div>}<section className="panel queue-panel"><div className="queue-summary"><span><strong>{items.length}</strong> itens na fila</span><span className="queue-note">Ordenação: prioridade · prazo · espera</span></div>{loading ? <div className="queue-loading">Carregando fila…</div> : items.length === 0 ? <div className="empty-state"><span>✓</span><strong>Nenhum item nesta fila</strong><p>Novas solicitações aparecerão aqui quando estiverem no escopo do setor.</p></div> : <div className="queue-table-wrap"><table className="queue-table"><caption className="sr-only">Fila de exames</caption><thead><tr><th>Paciente</th><th>Exame</th><th>Prioridade</th><th>Status</th><th>Prazo</th><th>Próxima ação</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.id} className={item.overdue ? "row-overdue" : ""}><td><Link href={`/requests/${item.requestId}`} className="table-patient"><strong>{item.patient.displayName}</strong><small>{item.patient.species} · {item.patient.externalId}</small></Link></td><td><strong>{item.service.name}</strong><small>{item.requestCode}</small></td><td><PriorityBadge priority={item.priority} /></td><td><StatusBadge status={item.status} /></td><td><span className={item.overdue ? "text-danger" : ""}>{item.overdue ? "Atrasado" : formatRelativeTime(item.dueAt)}</span></td><td><span className="next-action">{item.nextAction}</span></td><td><Link href={`/requests/${item.requestId}`} className="row-arrow" aria-label={`Abrir ${item.service.name}`}>→</Link></td></tr>)}</tbody></table></div>}</section></div>;
}
