"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import type { ItemState, Priority } from "@cvg/contracts";
import { apiFetch, formatRelativeTime } from "./api-client";
import { PriorityBadge, StatusBadge } from "./status-badge";

interface Request { id: string; requestCode: string; priority: Priority; aggregateStatus: string; createdAt: string; patient: { displayName: string; species: string; sex: string; externalId: string; ownerLabel: string }; items: Array<{ id: string; status: ItemState; priority: Priority; dueAt: string; version: number; service: { name: string; workflowType: string } }> }
interface Event { id: string; eventType: string; newState?: string; occurredAt: string }
export function RequestDetail({ requestId }: { requestId: string }) { const [request, setRequest] = useState<Request | null>(null); const [timeline, setTimeline] = useState<Event[]>([]); const [error, setError] = useState(""); useEffect(() => { void Promise.all([apiFetch<Request>(`/diagnostic-requests/${requestId}`), apiFetch<Event[]>(`/timeline?requestId=${encodeURIComponent(requestId)}`)]).then(([nextRequest, events]) => { setRequest(nextRequest); setTimeline(events); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Não foi possível carregar o contexto.")); }, [requestId]); if (error) return <div className="error-state" role="alert"><strong>Contexto indisponível</strong><span>{error}</span><Link className="button button-ghost" href="/">Voltar à visão geral</Link></div>; if (!request) return <div className="loading-state">Carregando contexto…</div>; return <div className="detail-page"><Link href="/" className="back-link">← Visão geral</Link><div className="detail-heading"><div><p className="eyebrow">Solicitação {request.requestCode}</p><h1>{request.patient.displayName} <em>em acompanhamento.</em></h1><p className="page-lede">{request.patient.species} · {request.patient.sex} · {request.patient.externalId} · tutor {request.patient.ownerLabel}</p></div><PriorityBadge priority={request.priority} /></div><div className="detail-grid"><section className="panel detail-items"><div className="panel-heading"><div><p className="eyebrow">Itens independentes</p><h2>{request.items.length} exames nesta solicitação</h2></div><span className="aggregate-status">{request.aggregateStatus.replaceAll("_", " ")}</span></div>{request.items.map((item) => <article className="detail-item" key={item.id}><div className="detail-item-icon">{item.service.workflowType === "LABORATORY" ? "✣" : "◌"}</div><div className="detail-item-copy"><h3>{item.service.name}</h3><small>{item.service.workflowType === "LABORATORY" ? "Laboratório" : "Imagem"} · prazo {formatRelativeTime(item.dueAt)}</small></div><StatusBadge status={item.status} /><Link href={`/requests/${request.id}#${item.id}`} className="row-arrow" aria-label={`Ver ${item.service.name}`}>→</Link></article>)}</section><section className="panel timeline-panel"><div className="panel-heading"><div><p className="eyebrow">Fonte de verdade</p><h2>Timeline</h2></div><span className="timeline-count">{timeline.length} eventos</span></div><ol className="timeline">{timeline.map((event) => <li key={event.id}><span className="timeline-marker" /><div><strong>{event.eventType.replace(/([A-Z])/g, " $1").trim()}</strong><small>{event.newState ? `Estado: ${event.newState}` : "Ação registrada"} · {formatRelativeTime(event.occurredAt)}</small></div></li>)}</ol></section></div></div>; }
